name: flourish
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

# packages
dependencies:
  flutter:
    sdk: flutter

  # utility packages
  google_fonts: ^4.0.4

  # icons
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  intl: ^0.20.2
  http: ^1.3.0
  logger: ^2.5.0
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.0+3
  line_awesome_flutter: ^3.0.1
  image_picker: ^1.1.2
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  supabase_flutter: ^2.8.3

  # state management

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # local assets
  assets:
    - assets/images/
    - assets/logo/
    - assets/images/on_boarding/
    - assets/images/authentication/
